package com.example.kwai_win;/* autogenerated by Processing revision 1282 on 2022-04-14 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import ddf.minim.*;
import ddf.minim.analysis.*;
import ddf.minim.effects.*;
import ddf.minim.signals.*;
import ddf.minim.spi.*;
import ddf.minim.ugens.*;
import java.util.Random;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class happyMat extends PApplet {








Minim minim;
AudioPlayer audio;
BeatDetect beat;

float var1;
float var2;
float eRadius;


//MAIN SETUP

 public void setup () {
  /* size commented out by preprocessor */;
  /* smooth commented out by preprocessor */;
  surface.setResizable(true);
    background (0);
  frameRate(30);  
  
  //experimenting with BeatDetect
  beat = new BeatDetect();
  ellipseMode(RADIUS);
  eRadius = 20;
   
//AUDIO PROCESSING DONE HERE.
  minim = new Minim(this);
  audio = minim.loadFile("summer-happy.mp3");    
  audio.loop();
}

 public void draw () {
  fill(0,50);  
  noStroke();  //Disables drawing the stroke (outline).
  rect(0, 0, width, height);
  translate(width/2, height/2);    //https://processing.org/reference/translate_.html
  
  int size = audio.bufferSize();
  
  
  // BeatDetect drawing stuff
  
  beat.detect(audio.mix);
  if ( beat.isOnset() ) eRadius = 100;
  
  
  fill(204, 102, 0);
  ellipse(0, 0, eRadius, eRadius);
  eRadius *= 0.95f;
  if ( eRadius < 20 ) eRadius = 20;

  // regular for loop patterns
  
  for (int i = 0; i < size - 1; i++) {
    float angle = sin(i+var1) * 10;
    
    float x = sin(radians(i)*(1000/angle));
    float y = cos(radians(i)*(1000/angle));
    
    float x3 = sin(radians(i)*(600/angle));
    float y3 = cos(radians(i)*(600/angle));

    float x4 = sin(radians(i))*(1250/angle); 
    float y4 = cos(radians(i))*(1250/angle);
    
    float x5 = sin(radians(i))*(1400/angle); 
    float y5 = cos(radians(i))*(1400/angle);
    
// YELLOW, WHITE AND ORANGE
    fill (0xFFFFE162, 90); //yellow
    circle(x, y, audio.right.get(i)*100);
 
    fill (0xFFFFF8E5, 80); // off white
    circle(x3, y3, audio.right.get(i));
    
    fill (0xFFFFB085, 100); // pastel orange
    circle(x4, y4, audio.right.get(i)*20);
    
    for (int j = i; j > 0; j = j - 100) {
    fill (0xFFFFF8E5, 50); // white
    circle(x5, y5, audio.right.get(i)*10);
   }
 
  }
  
  var1 += 0.01f;
  var2 += 0.05f;
 
}


  public void settings() { size(1080, 1080);
smooth(8); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "happyMat" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
