package com.example.kwai_win;/* autogenerated by Processing revision 1281 on 2022-03-16 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import ddf.minim.*;
import ddf.minim.analysis.*;
import ddf.minim.effects.*;
import ddf.minim.signals.*;
import ddf.minim.spi.*;
import ddf.minim.ugens.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sleep extends PApplet {

//Ameer: this is the relax preset with waves
//float gl = round(sin(radians(i+150)) * (15*round(height / 100)) + (height * 3/4) - (round(sin(radians(150)))));







float fps = 30; 
float smoothingFactor = 0.25f;
AudioPlayer player;
FFT fft;
Minim minim;
int bands = 256; // must be multiple of two
float[] spectrum = new float[bands];
float[] sum = new float[bands];
float unit;
int groundLineY;
int sphereRadius;
float spherePrevX;
float spherePrevY;
int yOffset;
boolean initialStatic = true;
float[] extendingSphereLinesRadius;
PVector center;
float var1;
float var2;
//Main Setup:
 public void settings() {
  size(1080, 1080);
  smooth(8);
}

 public void setup() {
  frameRate(fps);
  unit = height / 100; 
  groundLineY = height * 2/3; 
  center = new PVector(width / 2, height * 3/4);
  minim = new Minim(this);
  player = minim.loadFile("sleep.mp3", 2048);
  
  player.loop();
  fft = new FFT( player.bufferSize(), player.sampleRate() );
  fft.linAverages(256);
  //noCursor();
  background (0);
}

 public void drawStatic(){
  if (initialStatic) {
    extendingSphereLinesRadius = new float[241];
 
    for (int angle = 0; angle <= 240; angle += 7) {
      extendingSphereLinesRadius[angle] = map(random(1), 0, 1, sphereRadius, sphereRadius * 7);
    }
 
    initialStatic = false;
  }
  
  for (int angle = 0; angle <= 240; angle += 1.5f) {
    float x = round(cos(radians(angle + 150)) * sphereRadius + center.x);
    float y = round(sin(radians(angle + 150)) * sphereRadius + groundLineY - yOffset);
    float xDestination = x;
    float yDestination = y;
  
  for (int i = sphereRadius; i <= extendingSphereLinesRadius[angle]; i++) {
      float x2 = cos(radians(angle + 150)) * i + center.x;
      float y2 = sin(radians(angle + 150)) * i + groundLineY - yOffset;
 
      if (y2 <= getGroundY(x2)) { // Make sure it doesn't go into ground
        xDestination = x2;
        yDestination = y2;
      }
    }
  stroke(255);
  //if (y <= getGroundY(x)) line(x, y, xDestination, yDestination);
  }   
}


//curves:
 public void drawAll(float[] sum) {
  sphereRadius = 15 * round(unit);
  spherePrevX = 0;
  spherePrevY = 0;
  yOffset = round(sin(radians(150)) * sphereRadius);
  drawStatic();
  float x = 0;
  float y = 0;
  int surrCount = 1;
  boolean direction = false;
  while (x < width * 1.5f && x > 0 - width / 2){
    float surroundingRadius;
    float surrRadMin = sphereRadius + sphereRadius * 1/2 * surrCount;
    float surrRadMax = surrRadMin + surrRadMin * 1/8;
    float surrYOffset;
    float addon = frameCount * 1.5f;
    if(direction) addon = addon * 1.5f;
    
    //player.bufferSize() - 1 dancing circular waves in the back
    for (float angle = 0; angle <= 240; angle += 1.5f){
      surroundingRadius = map(sin(radians(angle * 7 + addon)), -1, 1, surrRadMin, surrRadMax); // Faster rotation through angles, radius oscillates
      surrYOffset = sin(radians(150)) * surroundingRadius;
      x = round(cos(radians(angle + 150)) * surroundingRadius + center.x);
      y = round(sin(radians(angle + 150)) * surroundingRadius + getGroundY(x) - surrYOffset);
      noStroke();
      fill(map(surroundingRadius, surrRadMin, surrRadMax, 100, 255));
      if( angle % 2 == 0) {
        fill(0xFF95D1CC , 200);//cool green
        circle(x, y, 3* unit / 10.24f);
      } else {
        fill(0xFFDFF6FF, 200); //cool blue
        circle(x, y, 3* unit / 10.24f);
      }
      //noFill();
    }
    
    //sound sphere in the middle:
    //241 or player.bufferSize() - 1
    //for (int i = 0; i < player.bufferSize() - 1; i++){
    //  float angle = sin(i+var1)* 10; 
    //  float angle2 = sin(i+var2)* 300; 
    //  //float x = sin(radians(i))*(angle2+30); 
    //  //float y = cos(radians(i))*(angle2+30);
    //  float x3 = sin(radians(i))*(500/angle); 
    //  float y3 = cos(radians(i))*(500/angle);
    //  fill (#00ffff, 90); //blue
    //  ellipse(x3+540, y3+650, player.right.get(i)*30, player.left.get(i)*30);
      
    //}
    
    direction = !direction;
    surrCount += 1;
    
    // Ground line
    for (int groundX = 0; groundX <= width; groundX+=3) {
      float groundY = getGroundY(groundX);
      noStroke();
      //fill(255);
      if(groundX % 2 == 0){
        fill(0xFFFFFFFF , 200);
        circle(groundX, groundY, 1.8f * unit / 10.24f);
      } else {
        fill(0xFF00FFFF , 200);
        circle(groundX, groundY+50, 1.8f * unit / 10.24f);
      }
      groundY = getGroundY2(groundX);
      fill(0xFF2E4C6D , 200);
      circle(groundX, groundY+50, 1.8f * unit / 10.24f);
      groundY = getGroundY2(groundX);
      fill(0xFFDADDFC , 200);
      circle(groundX, groundY+10, 1.8f * unit / 10.24f);
      fill(0xFFFC997C , 200);
      circle(groundX, groundY+100, 1.8f * unit / 10.24f);
      //noFill();  
    }
  }
}


  // Get the Y position at position X of ground sine wave
 public float getGroundY(float groundX) {
  float angle = 1.1f * groundX / unit * 10.24f;
  float groundY = sin(radians(angle + frameCount * 2)) * unit * 1.25f + groundLineY - unit * 1.25f;
  return groundY;
}

 public float getGroundY2(float groundX) {
  float angle = 1.1f * groundX / unit * 10.24f;
  float groundY = cos(radians(angle + frameCount * 2)) * unit * 1.25f + groundLineY - unit * 1.25f;
  return groundY;
}


 public void draw() {
  fft.forward(player.mix);
  spectrum = new float[bands];
  for(int i = 0; i < fft.avgSize(); i++){
    spectrum[i] = fft.getAvg(i) / 2;
    // Smooth the FFT spectrum data by smoothing factor
    sum[i] += (abs(spectrum[i]) - sum[i]) * smoothingFactor;
  }
 
  // Reset canvas
  fill(0);
  noStroke();
  rect(0, 0, width, height);
  noFill();
 
  drawAll(sum);
}


  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sleep" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
